#
#  EXEMPLO: Como adicionar projeto2
#

version: '3.8'

# Nome do projeto (containers ficarão dentro de "api")
name: api

services:
  api:
    # ← aqui colocar nome do projeto ex. clickjoias etc...!
    image: api_mvc:latest #  Usa a IMAGEM BASE que você builda neste repo
    container_name: projeto2_api #  Mude o nome para o seu projeto
    volumes:
      - ./api:/var/www/html
    ports:
      - "8091:80" #  Mude a porta conforme desejar
    environment:
      DB_HOST: mysql_shared #  Host do MySQL compartilhado (nome do container)
      DB_PORT: 3307 #  Porta mapeada pelo MySQL compartilhado
      DB_NAME: projeto2 #  Mude o database
      DB_USER: root
      DB_PASS: root
    networks:
      - shared_network
    command: >
      sh -c "
        if [ ! -d 'vendor' ]; then
          composer install --no-interaction --optimize-autoloader;
        fi &&
        apache2-foreground
      "
    restart: unless-stopped

# ✅ Define a rede externa (criada pelo docker-infra)
networks:
  shared_network:
    external: true
